# Generated by Django 4.1.5 on 2023-01-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
