# Generated by Django 4.1.5 on 2023-01-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDApp', '0002_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
